"""로고를 폰트 글리프로 굽는 어댑터.

터미널 프롬프트는 텍스트만 그릴 수 있어 이미지를 못 넣는다. 로고를 사용자 정의 영역(PUA)
코드포인트의 글리프로 만들면 프롬프트에서 한 글자로 출력할 수 있다.

포맷은 sbix — macOS(Core Text)가 지원하는 컬러 비트맵 글리프 포맷이고 Apple Color Emoji가
쓰는 것과 같아 렌더링이 확실하다. OT-SVG는 macOS 지원이 불안정해 쓰지 않는다.
"""
import io
import json
from pathlib import Path

from PIL import Image
from fontTools.ttLib import TTFont, newTable
from fontTools.ttLib.tables._g_l_y_f import Glyph as EmptyGlyph
from fontTools.ttLib.tables.sbixGlyph import Glyph as SbixGlyph
from fontTools.ttLib.tables.sbixStrike import Strike

from ..domain import palette

FAMILY = "OhMyTerminal Brand"
PUA_START = 0xE900
STRIKE_PPEM = 128          # 비트맵 해상도. 낮으면 고해상도 화면에서 뭉갠다


class SbixFontWriter:
    def __init__(self, base_font: Path):
        self.base_font = base_font

    def write(self, brands, output_root: Path):
        usable = [brand for brand in brands if brand.has_logo]
        if not usable:
            return None, {}

        font = TTFont(self.base_font)
        metrics = font["hmtx"].metrics
        # 터미널은 고정폭이다 — 로고도 기존 글자와 같은 폭이어야 정렬이 안 깨진다.
        advance = metrics["space"][0] if "space" in metrics else font["head"].unitsPerEm // 2

        names, mapping = [], {}
        for index, brand in enumerate(usable):
            name = f"brandlogo.{brand.key}"
            names.append(name)
            mapping[PUA_START + index] = name
            font["glyf"].glyphs[name] = EmptyGlyph()      # sbix는 외곽선 없이 비트맵만 쓴다
            metrics[name] = (advance, 0)

        font.setGlyphOrder(font.getGlyphOrder() + names)
        font["maxp"].numGlyphs = len(font.getGlyphOrder())
        for table in font["cmap"].tables:
            if table.isUnicode():
                table.cmap.update(mapping)

        strike = Strike(ppem=STRIKE_PPEM, resolution=72)
        for brand in usable:
            tint = None if brand.keeps_original_colour else palette.logo_tint(brand)[0]
            strike.glyphs[f"brandlogo.{brand.key}"] = SbixGlyph(
                glyphName=f"brandlogo.{brand.key}", graphicType="png ",
                imageData=self._render(Path(brand.logo_path), tint),
                originOffsetX=0, originOffsetY=-int(STRIKE_PPEM * 0.12))

        sbix = newTable("sbix")
        sbix.version, sbix.flags, sbix.numStrikes = 1, 1, 1
        sbix.strikes = {STRIKE_PPEM: strike}
        font["sbix"] = sbix

        # PostScript 이름(nameID 6)에는 공백을 못 쓰고, iTerm2가 이 이름으로 폰트를 찾는다.
        postscript = FAMILY.replace(" ", "") + "-Regular"
        for record in font["name"].names:
            replacement = {1: FAMILY, 3: f"{FAMILY}; generated by tools/build.py",
                           4: f"{FAMILY} Regular", 6: postscript}.get(record.nameID)
            if replacement:
                record.string = replacement

        output = output_root / "fonts" / f"{postscript}.ttf"
        output.parent.mkdir(parents=True, exist_ok=True)
        font.save(output)

        codepoints = {brand.key: PUA_START + index for index, brand in enumerate(usable)}
        (output_root / "fonts" / "codepoints.json").write_text(
            json.dumps({"family": FAMILY, "postscript": postscript, "codepoints": codepoints},
                       indent=2) + "\n")
        return output, {key: chr(code) for key, code in codepoints.items()}

    @staticmethod
    def _render(path: Path, tint):
        logo = Image.open(path).convert("RGBA")
        scale = STRIKE_PPEM / max(logo.width, logo.height)
        resized = logo.resize((max(1, round(logo.width * scale)), max(1, round(logo.height * scale))),
                              Image.LANCZOS)
        if tint is not None:
            coloured = Image.new("RGBA", resized.size, tuple(tint) + (0,))
            coloured.putalpha(resized.getchannel("A"))
            resized = coloured
        canvas = Image.new("RGBA", (STRIKE_PPEM, STRIKE_PPEM), (0, 0, 0, 0))
        canvas.paste(resized, ((STRIKE_PPEM - resized.width) // 2,
                               (STRIKE_PPEM - resized.height) // 2), resized)
        buffer = io.BytesIO()
        canvas.save(buffer, format="PNG")
        return buffer.getvalue()
