# ─────────────────────────────────────────────────────────────────────────────
#  이 파일은 oh-my-terminal 빌더가 생성한다. 직접 고치지 말고 brands/*.yaml을 고칠 것.
#  순수 zsh다 — python·curl 등 외부 명령에 의존하지 않는다.
#  ~/.p10k.zsh 를 source 한 '뒤에' 이 파일을 source 해야 한다.
# ─────────────────────────────────────────────────────────────────────────────

autoload -Uz add-zsh-hook

typeset -g  _brand_dir_content=""
typeset -gA _brand_gradient_cache=()

# 터미널은 그라데이션을 모른다 — 글자마다 배경색을 조금씩 바꿔 흉내낸다.
# 결과를 REPLY에 넣는다. 예전에는 호출부가 $( )로 감쌌는데, 그러면 함수가 서브셸에서
# 돌아 캐시에 쓴 값이 부모로 돌아오지 않는다 — 캐시가 한 번도 히트하지 않았고
# 프롬프트를 그릴 때마다 fork + 전체 재계산이었다.
_brand_gradient() {
  local text=$1 start=$2 end=$3 dark_fg=$4 light_fg=$5
  local -i n=${#text} i
  local -i sr=$((16#${start[2,3]})) sg=$((16#${start[4,5]})) sb=$((16#${start[6,7]}))
  local -i er=$((16#${end[2,3]}))   eg=$((16#${end[4,5]}))   eb=$((16#${end[6,7]}))
  local out="" previous_fg=""
  for (( i = 1; i <= n; i++ )); do
    local -F t=$(( n > 1 ? (i - 1.0) / (n - 1.0) : 0 ))
    local -i r=$(( sr + (er - sr) * t )) g=$(( sg + (eg - sg) * t )) b=$(( sb + (eb - sb) * t ))
    # 배경이 어두워지는 지점에서 글자색을 뒤집지 않으면 경로 끝이 안 읽힌다.
    local -i luma=$(( (r * 299 + g * 587 + b * 114) / 1000 ))
    local fg=$(( luma > 140 ? 1 : 2 ))
    fg=${${fg/1/$dark_fg}/2/$light_fg}
    printf -v out '%s%%K{#%02X%02X%02X}' "$out" $r $g $b
    [[ $fg == $previous_fg ]] || { printf -v out '%s%%F{%s}' "$out" "$fg"; previous_fg=$fg }
    out+="${text[i]}"
  done
  REPLY=$out
}

# 디렉터리가 바뀔 때 한 번만 굽는다. 프롬프트는 변수만 참조하므로 fork가 없다.
# 경로는 p10k의 P9K_CONTENT에서 받지 않는다 — 두 번째 프롬프트부터 '이미 확장된' 값이
# 들어와 우리가 넣은 %K{...} 위에 색이 또 입혀졌다 (프롬프트에 리터럴 %K{ 가 찍혔다).
_brand_apply() {
  local start end dark light icon
  case $PWD in
    ${HOME}/Desktop/baemin(|/*)) start='#0CEFD3'; end='#089B89'; dark='#222222'; light='#222222'; icon=' ' ;;
    ${HOME}/Desktop/banksalad(|/*)) start='#13BD7E'; end='#0F9362'; dark='#111111'; light='#111111'; icon=' ' ;;
    ${HOME}/Desktop/coupang(|/*)) start='#292929'; end='#121212'; dark='#000000'; light='#919191'; icon=' ' ;;
    ${HOME}/Desktop/kakao(|/*)) start='#FEE500'; end='#B7A500'; dark='#333333'; light='#333333'; icon=' ' ;;
    ${HOME}/Desktop/karrot(|/*)) start='#FF7E36'; end='#E06F30'; dark='#212124'; light='#212124'; icon=' ' ;;
    ${HOME}/Desktop/line(|/*)) start='#06C755'; end='#048F3D'; dark='#000000'; light='#000000'; icon=' ' ;;
    ${HOME}/Desktop/musinsa(|/*)) start='#292929'; end='#121212'; dark='#000000'; light='#919191'; icon=' ' ;;
    ${HOME}/Desktop/naver(|/*)) start='#03C75A'; end='#029B46'; dark='#16181D'; light='#16181D'; icon=' ' ;;
    ${HOME}/Desktop/nol(|/*)) start='#3549FF'; end='#182173'; dark='#F5F6F9'; light='#F5F6F9'; icon=' ' ;;
    ${HOME}/Desktop/socar(|/*)) start='#006EEB'; end='#00326A'; dark='#354153'; light='#FBFBFC'; icon=' ' ;;
    ${HOME}/Desktop/toss(|/*)) start='#0064FF'; end='#002D73'; dark='#191F28'; light='#F5F6F9'; icon=' ' ;;
    *) _brand_dir_content=""; return ;;
  esac
  local text="${icon}${(%):-%~}"
  local key="$text|$start|$end"
  if [[ -n ${_brand_gradient_cache[$key]} ]]; then
    _brand_dir_content=${_brand_gradient_cache[$key]}
  else
    _brand_gradient "$text" "$start" "$end" "$dark" "$light"
    _brand_dir_content=$REPLY
    _brand_gradient_cache[$key]=$REPLY
  fi
}
add-zsh-hook chpwd _brand_apply
_brand_apply

# 프롬프트 첫 칸. 회사 폴더 안에서는 비워 칸 자체를 숨기고(로고는 경로 세그먼트가 그린다),
# 밖에서는 원래의 OS 아이콘을 보여준다.
# case 패턴에 ~ 를 쓰면 zsh가 틸드 확장을 해버려 절대 안 맞는다 — $PWD로 비교한다.
# 이 세그먼트만은 fork를 피할 수 없다: p10k가 os_icon을 정적으로 캐싱해 변수 참조로는
# 디렉터리 변경이 반영되지 않는다(확인함). 커스텀 세그먼트는 매 프롬프트 재실행된다.
_brand_logo_segment() {
  case $PWD in
    ${HOME}/Desktop/baemin(|/*)) return ;;
    ${HOME}/Desktop/banksalad(|/*)) return ;;
    ${HOME}/Desktop/coupang(|/*)) return ;;
    ${HOME}/Desktop/kakao(|/*)) return ;;
    ${HOME}/Desktop/karrot(|/*)) return ;;
    ${HOME}/Desktop/line(|/*)) return ;;
    ${HOME}/Desktop/musinsa(|/*)) return ;;
    ${HOME}/Desktop/naver(|/*)) return ;;
    ${HOME}/Desktop/nol(|/*)) return ;;
    ${HOME}/Desktop/socar(|/*)) return ;;
    ${HOME}/Desktop/toss(|/*)) return ;;
  esac
  print -rn -- $'\uf179'
}

typeset -g POWERLEVEL9K_DIR_CLASSES=(
  '~/Desktop/baemin(|/*)'          BRAND_BAEMIN       ''
  '~/Desktop/banksalad(|/*)'       BRAND_BANKSALAD    ''
  '~/Desktop/coupang(|/*)'         BRAND_COUPANG      ''
  '~/Desktop/kakao(|/*)'           BRAND_KAKAO        ''
  '~/Desktop/karrot(|/*)'          BRAND_KARROT       ''
  '~/Desktop/line(|/*)'            BRAND_LINE         ''
  '~/Desktop/musinsa(|/*)'         BRAND_MUSINSA      ''
  '~/Desktop/naver(|/*)'           BRAND_NAVER        ''
  '~/Desktop/nol(|/*)'             BRAND_NOL          ''
  '~/Desktop/socar(|/*)'           BRAND_SOCAR        ''
  '~/Desktop/toss(|/*)'            BRAND_TOSS         ''
  '*'                              DEFAULT            ''
)

# DEFAULT 클래스는 값을 정의하지 않는다 — p10k가 기존 POWERLEVEL9K_DIR_* 로 폴백하므로
# 회사 경로 밖에서는 원래 쓰던 프롬프트가 그대로 유지된다.

# Baemin
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Banksalad
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Coupang
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Kakao
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Karrot
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# LINE
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Musinsa
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Naver
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# NOL
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# SOCAR
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# Toss
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_CONTENT_EXPANSION='${_brand_dir_content}'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_CONTENT_EXPANSION='${_brand_dir_content}'

# os_icon 자리를 커스텀 세그먼트로 바꾼다. os_icon은 p10k가 정적 세그먼트로 캐싱해
# 디렉터리가 바뀌어도 갱신되지 않기 때문이다 (변수 참조로도 안 된다 — 확인함).
#
# 사용자의 배열을 통째로 대입하지 않는다. 예전에는 (custom_brandlogo dir vcs)로 못박아
# 회사 폴더 밖에서도 남의 프롬프트 구성이 이 셋으로 고정됐다. os_icon 항목만 바꿔치기한다.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[@]/os_icon/custom_brandlogo})
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO='_brand_logo_segment'
# 색도 사용자의 os_icon 값을 따른다. 하드코딩하면 다른 사람에게 틀린 색이 된다.
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO_BACKGROUND=${POWERLEVEL9K_OS_ICON_BACKGROUND:-7}
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO_FOREGROUND=${POWERLEVEL9K_OS_ICON_FOREGROUND:-232}
