# ─────────────────────────────────────────────────────────────────────────────
#  이 파일은 tools/build.py가 생성한다. 직접 고치지 말고 brands/*.yaml을 고칠 것.
#  순수 zsh다 — python·curl 등 외부 명령에 의존하지 않는다.
#  ~/.p10k.zsh 를 source 한 '뒤에' 이 파일을 source 해야 한다.
# ─────────────────────────────────────────────────────────────────────────────

typeset -gA _brand_gradient_cache=()

# 터미널은 그라데이션을 모른다 — 글자마다 배경색을 조금씩 바꿔 흉내낸다.
_brand_gradient() {
  local text=$1 start=$2 end=$3 dark_fg=$4 light_fg=$5
  local -i n=${#text} i
  local -i sr=$((16#${start[2,3]})) sg=$((16#${start[4,5]})) sb=$((16#${start[6,7]}))
  local -i er=$((16#${end[2,3]}))   eg=$((16#${end[4,5]}))   eb=$((16#${end[6,7]}))
  local out="" previous_fg=""
  for (( i = 1; i <= n; i++ )); do
    local -F t=$(( n > 1 ? (i - 1.0) / (n - 1.0) : 0 ))
    local -i r=$(( sr + (er - sr) * t )) g=$(( sg + (eg - sg) * t )) b=$(( sb + (eb - sb) * t ))
    # 배경이 어두워지는 지점에서 글자색을 뒤집지 않으면 경로 끝이 안 읽힌다.
    local -i luma=$(( (r * 299 + g * 587 + b * 114) / 1000 ))
    local fg=$(( luma > 140 ? 1 : 2 ))
    fg=${${fg/1/$dark_fg}/2/$light_fg}
    printf -v out '%s%%K{#%02X%02X%02X}' "$out" $r $g $b
    [[ $fg == $previous_fg ]] || { printf -v out '%s%%F{%s}' "$out" "$fg"; previous_fg=$fg }
    out+="${text[i]}"
  done
  print -r -- "$out"
}

# 경로는 P9K_CONTENT에서 받지 않는다. p10k가 두 번째 프롬프트부터 '이미 확장된' 값을
# 그 변수에 담아, 우리가 넣은 %K{...} 위에 색이 또 입혀지는 이중 적용이 일어난다
# (프롬프트에 리터럴 %K{ 가 그대로 찍혔다). $PWD 기반으로 직접 만든다.
_brand_gradient_cached() {
  local text="$1${(%):-%~}"
  local key="$text|$2|$3|$4|$5"
  [[ -n ${_brand_gradient_cache[$key]} ]] || \
    _brand_gradient_cache[$key]=$(_brand_gradient "$text" "$2" "$3" "$4" "$5")
  print -r -- ${_brand_gradient_cache[$key]}
}

# 프롬프트 첫 칸. 회사 폴더 안에서는 비워 칸 자체를 숨기고(로고는 경로 세그먼트가 그린다),
# 밖에서는 원래의 OS 아이콘을 보여준다.
# case 패턴에 ~ 를 쓰면 zsh가 틸드 확장을 해버려 절대 안 맞는다 — $PWD로 비교한다.
_brand_logo_segment() {
  case $PWD in
    ${HOME}/Desktop/baemin(|/*)) return ;;
    ${HOME}/Desktop/banksalad(|/*)) return ;;
    ${HOME}/Desktop/coupang(|/*)) return ;;
    ${HOME}/Desktop/kakao(|/*)) return ;;
    ${HOME}/Desktop/karrot(|/*)) return ;;
    ${HOME}/Desktop/line(|/*)) return ;;
    ${HOME}/Desktop/musinsa(|/*)) return ;;
    ${HOME}/Desktop/naver(|/*)) return ;;
    ${HOME}/Desktop/nol(|/*)) return ;;
    ${HOME}/Desktop/socar(|/*)) return ;;
    ${HOME}/Desktop/toss(|/*)) return ;;
  esac
  print -rn -- $''
}

typeset -g POWERLEVEL9K_DIR_CLASSES=(
  '~/Desktop/baemin(|/*)'        BRAND_BAEMIN       ''
  '~/Desktop/banksalad(|/*)'     BRAND_BANKSALAD    ''
  '~/Desktop/coupang(|/*)'       BRAND_COUPANG      ''
  '~/Desktop/kakao(|/*)'         BRAND_KAKAO        ''
  '~/Desktop/karrot(|/*)'        BRAND_KARROT       ''
  '~/Desktop/line(|/*)'          BRAND_LINE         ''
  '~/Desktop/musinsa(|/*)'       BRAND_MUSINSA      ''
  '~/Desktop/naver(|/*)'         BRAND_NAVER        ''
  '~/Desktop/nol(|/*)'           BRAND_NOL          ''
  '~/Desktop/socar(|/*)'         BRAND_SOCAR        ''
  '~/Desktop/toss(|/*)'          BRAND_TOSS         ''
  '*'                            DEFAULT            ''
)

# DEFAULT 클래스는 값을 정의하지 않는다 — p10k가 기존 POWERLEVEL9K_DIR_* 로 폴백하므로
# 회사 경로 밖에서는 원래 쓰던 프롬프트가 그대로 유지된다.

# Baemin
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0CEFD3" "#089B89" "#222222" "#222222")'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0CEFD3" "#089B89" "#222222" "#222222")'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_BACKGROUND='#089B89'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_SHORTENED_FOREGROUND='#165950'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_ANCHOR_FOREGROUND='#222222'
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BAEMIN_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0CEFD3" "#089B89" "#222222" "#222222")'

# Banksalad
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#13BD7E" "#0F9362" "#111111" "#111111")'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#13BD7E" "#0F9362" "#111111" "#111111")'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_BACKGROUND='#0F9362'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_SHORTENED_FOREGROUND='#104C36'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_ANCHOR_FOREGROUND='#111111'
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_BANKSALAD_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#13BD7E" "#0F9362" "#111111" "#111111")'

# Coupang
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_COUPANG_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'

# Kakao
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FEE500" "#B7A500" "#333333" "#333333")'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FEE500" "#B7A500" "#333333" "#333333")'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_BACKGROUND='#B7A500'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_SHORTENED_FOREGROUND='#6E661C'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_ANCHOR_FOREGROUND='#333333'
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KAKAO_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FEE500" "#B7A500" "#333333" "#333333")'

# Karrot
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FF7E36" "#E06F30" "#212124" "#212124")'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FF7E36" "#E06F30" "#212124" "#212124")'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_BACKGROUND='#E06F30'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_SHORTENED_FOREGROUND='#774429'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_ANCHOR_FOREGROUND='#212124'
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_KARROT_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#FF7E36" "#E06F30" "#212124" "#212124")'

# LINE
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#06C755" "#048F3D" "#000000" "#000000")'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#06C755" "#048F3D" "#000000" "#000000")'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_BACKGROUND='#048F3D'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_SHORTENED_FOREGROUND='#02401C'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_LINE_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#06C755" "#048F3D" "#000000" "#000000")'

# Musinsa
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_BACKGROUND='#121212'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_SHORTENED_FOREGROUND='#080808'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_ANCHOR_FOREGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_MUSINSA_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#292929" "#121212" "#000000" "#919191")'

# Naver
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#03C75A" "#029B46" "#16181D" "#16181D")'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#03C75A" "#029B46" "#16181D" "#16181D")'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_BACKGROUND='#029B46'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_SHORTENED_FOREGROUND='#0D5330'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_ANCHOR_FOREGROUND='#16181D'
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NAVER_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#03C75A" "#029B46" "#16181D" "#16181D")'

# NOL
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#3549FF" "#182173" "#F5F6F9" "#F5F6F9")'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#3549FF" "#182173" "#F5F6F9" "#F5F6F9")'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_BACKGROUND='#182173'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_SHORTENED_FOREGROUND='#9196BD'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_ANCHOR_FOREGROUND='#F5F6F9'
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_NOL_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#3549FF" "#182173" "#F5F6F9" "#F5F6F9")'

# SOCAR
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#006EEB" "#00326A" "#354153" "#FBFBFC")'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#006EEB" "#00326A" "#354153" "#FBFBFC")'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_BACKGROUND='#00326A'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_SHORTENED_FOREGROUND='#1D3A5D'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_ANCHOR_FOREGROUND='#354153'
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_SOCAR_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#006EEB" "#00326A" "#354153" "#FBFBFC")'

# Toss
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0064FF" "#002D73" "#191F28" "#F5F6F9")'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NOT_WRITABLE_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0064FF" "#002D73" "#191F28" "#F5F6F9")'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_BACKGROUND='#002D73'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_SHORTENED_FOREGROUND='#0E254A'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_ANCHOR_FOREGROUND='#191F28'
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_BRAND_TOSS_NON_EXISTENT_CONTENT_EXPANSION='$(_brand_gradient_cached " " "#0064FF" "#002D73" "#191F28" "#F5F6F9")'

# os_icon을 커스텀 세그먼트로 교체한다. os_icon은 p10k가 정적 세그먼트로 캐싱해서
# 디렉터리가 바뀌어도 갱신되지 않는다 — 커스텀 세그먼트는 매 프롬프트 재실행된다.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_brandlogo dir vcs)
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO='_brand_logo_segment'
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO_BACKGROUND=7
typeset -g POWERLEVEL9K_CUSTOM_BRANDLOGO_FOREGROUND=232
